#Pull latest supported version of RethinkDB
FROM rethinkdb:latest

# Run init db
# ADD /sql/* /docker-entrypoint-initdb.d/

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

EXPOSE 8080